language: node_js
node_js:
- "10.6.0"

stages:
- test
- name: deploy
  if: tag IS present

jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: deploy
      script: npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master
          tags: true