language: node_js
node_js:
- "10.6.0"

stages:
- test
- deploy-github
- deploy-now-nightly
- deploy-now

jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: deploy-github
      script: npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        local-dir: './dist'
        keep-history: true
        on:
          branch: master
          tags: true
    - stage: deploy-now-nightly
      deploy:
        provider: script
        skip-cleanup: true
        script: npm run deploy:dev
        on:
          branch: master
          tags: false
    - stage: deploy-now
      deploy:
        provider: script
        skip-cleanup: true
        script: npm run deploy:prod
        on:
          branch: master
          tags: true