version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    commit_message:
      prefix: 'fix'
      prefix_development: 'chore'
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"    
