name: Check master branch

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install, lint and test
        run: |
          npm ci
          npm run lint
          npm run test
  deploy-staging:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') == false
    needs: [test]
    env:
      NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Deploy to staging
        run: npm run deploy:dev