name: Release production build

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install, lint and test
        run: |
          npm ci
          npm run lint
          npm run test
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
      NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_API_TOKEN }}
      SENTRY_ORG: eric-lambrecht-m5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Deploy to staging
        run: npm run deploy:dev
      - name: Set VERSION env
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF#refs/tags/})
      - name: Register sentry release
        run: |
          npm install @sentry/cli
          ./node_modules/.bin/sentry-cli releases new -p spotify-magician $VERSION
          ./node_modules/.bin/sentry-cli releases set-commits --auto $VERSION
          ./node_modules/.bin/sentry-cli releases deploys $VERSION new -e production
      - name: Deploy to production
        run: npm run deploy:prod